version: '3'
services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1@sha256:1084c64eed7d9318d028361c9aee398afdeb70d1816ce81d590b9450ec542c08
    container_name: es1
    environment:
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

    volumes:
      - /home/elaticsearch-container/es1/data:/usr/share/elasticsearch/data
      - /home/elaticsearch-container/es1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9201:9201
    restart: always
    networks:
      esnet:
        ipv4_address: 192.167.0.101
  es2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1@sha256:1084c64eed7d9318d028361c9aee398afdeb70d1816ce81d590b9450ec542c08
    container_name: es2
    environment:
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /home/elaticsearch-container/es2/data:/usr/share/elasticsearch/data
      - /home/elaticsearch-container/es2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9202:9202
    restart: always
    networks:
      esnet:
        ipv4_address: 192.167.0.102
  elasticsearch-head:
    image: tobias74/elasticsearch-head:6 
    container_name: es-head
    volumes:
       - /home/elaticsearch-container/head/Gruntfile.js:/usr/src/app/Gruntfile.js
       - /home/elaticsearch-container/head/_site/app.js:/usr/src/app/_site/app.js        
    ports:
       - "9100:9100" 
    restart: always
    networks:
      esnet:
        ipv4_address: 192.167.0.103


networks:
  esnet:
    driver: bridge
    ipam:
      config:
      - subnet: 192.167.0.0/24
